name: fajnosc
run-name: ${{ github.actor}} jazdaaa
on: 
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: |
          pip install pytest
      - run: python3 -m pytest tests.py
